// Viking Runner Sprite Images
// Running animation frames
export const viking_run = [
  'https://hwkaeeogqacgsfvbnfss.supabase.co/storage/v1/object/sign/viking_runner/viking.png?token=eyJraWQiOiJzdG9yYWdlLXVybC1zaWduaW5nLWtleV8xNjk2MjFhNC04ZjgxLTRhMWItODNhZC0yMzRkNzBmODFjYWIiLCJhbGciOiJIUzI1NiJ9.eyJ1cmwiOiJ2aWtpbmdfcnVubmVyL3Zpa2luZy5wbmciLCJpYXQiOjE3NjQ0MTgwODQsImV4cCI6NjQ5NDgxODA4NH0.qCOAxtRH6aQCpWvRhZQ6Zh1AK1-JJ5wGCXGcOiKPstY',
  'https://hwkaeeogqacgsfvbnfss.supabase.co/storage/v1/object/sign/viking_runner/viking2.png?token=eyJraWQiOiJzdG9yYWdlLXVybC1zaWduaW5nLWtleV8xNjk2MjFhNC04ZjgxLTRhMWItODNhZC0yMzRkNzBmODFjYWIiLCJhbGciOiJIUzI1NiJ9.eyJ1cmwiOiJ2aWtpbmdfcnVubmVyL3Zpa2luZzIucG5nIiwiaWF0IjoxNzY0NDE4MTQwLCJleHAiOjY0OTQ4MTgxNDB9.Do_ox2psZ4z2yiZHku60BabJP57Z3VNBru9Ceps2S4c',
  'https://hwkaeeogqacgsfvbnfss.supabase.co/storage/v1/object/sign/viking_runner/viking3.png?token=eyJraWQiOiJzdG9yYWdlLXVybC1zaWduaW5nLWtleV8xNjk2MjFhNC04ZjgxLTRhMWItODNhZC0yMzRkNzBmODFjYWIiLCJhbGciOiJIUzI1NiJ9.eyJ1cmwiOiJ2aWtpbmdfcnVubmVyL3Zpa2luZzMucG5nIiwiaWF0IjoxNzY0NDE4MTU4LCJleHAiOjY0OTQ4MTgxNTh9.mPnLITmDathz6T01tGr-K7P8tWpxFs9rwyELp62T8YY',
  'https://hwkaeeogqacgsfvbnfss.supabase.co/storage/v1/object/sign/viking_runner/viking4.png?token=eyJraWQiOiJzdG9yYWdlLXVybC1zaWduaW5nLWtleV8xNjk2MjFhNC04ZjgxLTRhMWItODNhZC0yMzRkNzBmODFjYWIiLCJhbGciOiJIUzI1NiJ9.eyJ1cmwiOiJ2aWtpbmdfcnVubmVyL3Zpa2luZzQucG5nIiwiaWF0IjoxNzY0NDE4MTc3LCJleHAiOjY0OTQ4MTgxNzd9.drq_MPN24Kg3dcHUq5DOI4Zpk6JxzFOG6YVxuJIQ3qs',
  'https://hwkaeeogqacgsfvbnfss.supabase.co/storage/v1/object/sign/viking_runner/viking5.png?token=eyJraWQiOiJzdG9yYWdlLXVybC1zaWduaW5nLWtleV8xNjk2MjFhNC04ZjgxLTRhMWItODNhZC0yMzRkNzBmODFjYWIiLCJhbGciOiJIUzI1NiJ9.eyJ1cmwiOiJ2aWtpbmdfcnVubmVyL3Zpa2luZzUucG5nIiwiaWF0IjoxNzY0NDE4MTk0LCJleHAiOjY0OTQ4MTgxOTR9.Ls5v88yJkB9Y7NFu4SK1g8HI-KcoHGZmMg0LFaiEg4s',
  'https://hwkaeeogqacgsfvbnfss.supabase.co/storage/v1/object/sign/viking_runner/viking6.png?token=eyJraWQiOiJzdG9yYWdlLXVybC1zaWduaW5nLWtleV8xNjk2MjFhNC04ZjgxLTRhMWItODNhZC0yMzRkNzBmODFjYWIiLCJhbGciOiJIUzI1NiJ9.eyJ1cmwiOiJ2aWtpbmdfcnVubmVyL3Zpa2luZzYucG5nIiwiaWF0IjoxNzY0NDE4MjA2LCJleHAiOjY0OTQ4MTgyMDZ9.0ASaqfEZ8kjO93uSb6AkdIA5Wi8wqBGRIZa_6YFQO2o',
  'https://hwkaeeogqacgsfvbnfss.supabase.co/storage/v1/object/sign/viking_runner/viking7.png?token=eyJraWQiOiJzdG9yYWdlLXVybC1zaWduaW5nLWtleV8xNjk2MjFhNC04ZjgxLTRhMWItODNhZC0yMzRkNzBmODFjYWIiLCJhbGciOiJIUzI1NiJ9.eyJ1cmwiOiJ2aWtpbmdfcnVubmVyL3Zpa2luZzcucG5nIiwiaWF0IjoxNzY0NDE4MjE5LCJleHAiOjY0OTQ4MTgyMTl9.Zfop-KJnhrWEu78e4bvkvXoxRDii2GtXUXoshQW9gKA'
];

// Jumping animation frames
export const viking_jump = [
  'https://hwkaeeogqacgsfvbnfss.supabase.co/storage/v1/object/sign/viking_runner/jump1.png?token=eyJraWQiOiJzdG9yYWdlLXVybC1zaWduaW5nLWtleV8xNjk2MjFhNC04ZjgxLTRhMWItODNhZC0yMzRkNzBmODFjYWIiLCJhbGciOiJIUzI1NiJ9.eyJ1cmwiOiJ2aWtpbmdfcnVubmVyL2p1bXAxLnBuZyIsImlhdCI6MTc2NDQxODI0NSwiZXhwIjo2NDk0ODE4MjQ1fQ.OzTJJJY8IL6iPaDMx363bUwFKkQ_6KU8EO11VuIbXGQ',
  'https://hwkaeeogqacgsfvbnfss.supabase.co/storage/v1/object/sign/viking_runner/jump2.png?token=eyJraWQiOiJzdG9yYWdlLXVybC1zaWduaW5nLWtleV8xNjk2MjFhNC04ZjgxLTRhMWItODNhZC0yMzRkNzBmODFjYWIiLCJhbGciOiJIUzI1NiJ9.eyJ1cmwiOiJ2aWtpbmdfcnVubmVyL2p1bXAyLnBuZyIsImlhdCI6MTc2NDQxODI1NCwiZXhwIjoxNzc3Mzc4MjU0fQ.V_JE7qKHJ0FsOZYHY9rULpWFbrBUlJVFve2PSqbls3w',
  'https://hwkaeeogqacgsfvbnfss.supabase.co/storage/v1/object/sign/viking_runner/jump3.png?token=eyJraWQiOiJzdG9yYWdlLXVybC1zaWduaW5nLWtleV8xNjk2MjFhNC04ZjgxLTRhMWItODNhZC0yMzRkNzBmODFjYWIiLCJhbGciOiJIUzI1NiJ9.eyJ1cmwiOiJ2aWtpbmdfcnVubmVyL2p1bXAzLnBuZyIsImlhdCI6MTc2NDQxODI2NCwiZXhwIjo2NDk0ODE4MjY0fQ.Ek6ZBRZKTteO7LvzO3W0GdRw0bGlyyDM8iecodjhGzA',
  'https://hwkaeeogqacgsfvbnfss.supabase.co/storage/v1/object/sign/viking_runner/jump4.png?token=eyJraWQiOiJzdG9yYWdlLXVybC1zaWduaW5nLWtleV8xNjk2MjFhNC04ZjgxLTRhMWItODNhZC0yMzRkNzBmODFjYWIiLCJhbGciOiJIUzI1NiJ9.eyJ1cmwiOiJ2aWtpbmdfcnVubmVyL2p1bXA0LnBuZyIsImlhdCI6MTc2NDQxODI3MywiZXhwIjo2NDk0ODE4MjczfQ.2p0I5j-FzUY0p5HocGzY7lvxf2l8psBEEf5SdGUDAE4',
  'https://hwkaeeogqacgsfvbnfss.supabase.co/storage/v1/object/sign/viking_runner/jump5.png?token=eyJraWQiOiJzdG9yYWdlLXVybC1zaWduaW5nLWtleV8xNjk2MjFhNC04ZjgxLTRhMWItODNhZC0yMzRkNzBmODFjYWIiLCJhbGciOiJIUzI1NiJ9.eyJ1cmwiOiJ2aWtpbmdfcnVubmVyL2p1bXA1LnBuZyIsImlhdCI6MTc2NDQxODI4NSwiZXhwIjo2NDk0ODE4Mjg1fQ.Kccjl4gNXqCtu6tsQJD1cVpqvdTBTKpEGGLhJ4K7z8M'
];

// Start/Idle animation frames
export const start_viking = [
  'https://hwkaeeogqacgsfvbnfss.supabase.co/storage/v1/object/sign/viking_runner/jump4.png?token=eyJraWQiOiJzdG9yYWdlLXVybC1zaWduaW5nLWtleV8xNjk2MjFhNC04ZjgxLTRhMWItODNhZC0yMzRkNzBmODFjYWIiLCJhbGciOiJIUzI1NiJ9.eyJ1cmwiOiJ2aWtpbmdfcnVubmVyL2p1bXA0LnBuZyIsImlhdCI6MTc2NDQxOTE2NywiZXhwIjo2NDk0ODE5MTY3fQ.GRZIoyJultKVD8Nc8VMtr-ZAZTHX3vlWTM7wxuZF5lE',
  'https://hwkaeeogqacgsfvbnfss.supabase.co/storage/v1/object/sign/viking_runner/jump5.png?token=eyJraWQiOiJzdG9yYWdlLXVybC1zaWduaW5nLWtleV8xNjk2MjFhNC04ZjgxLTRhMWItODNhZC0yMzRkNzBmODFjYWIiLCJhbGciOiJIUzI1NiJ9.eyJ1cmwiOiJ2aWtpbmdfcnVubmVyL2p1bXA1LnBuZyIsImlhdCI6MTc2NDQxOTE4NCwiZXhwIjo2NDk0ODE5MTg0fQ.1zgfxlVaNanriq0jLRSyTOMMD-Q4KRtoBTejldIO4ec',
  'https://hwkaeeogqacgsfvbnfss.supabase.co/storage/v1/object/sign/viking_runner/jump1.png?token=eyJraWQiOiJzdG9yYWdlLXVybC1zaWduaW5nLWtleV8xNjk2MjFhNC04ZjgxLTRhMWItODNhZC0yMzRkNzBmODFjYWIiLCJhbGciOiJIUzI1NiJ9.eyJ1cmwiOiJ2aWtpbmdfcnVubmVyL2p1bXAxLnBuZyIsImlhdCI6MTc2NDQxOTIwNCwiZXhwIjo2NDk0ODE5MjA0fQ.1c0_WhpiOrhTuhOBt7FksyuON4LCn4Sd7L7WlDr6kKk'
];

